### ISSUE TITLE
How to render components dynamically in a string variable?

### ISSUE THREAD

**Issue by Dan-Do** [ficusjs/ficusjs#8]
Hi @ducksoupdev
I want to do this
```javascript
createComponent('hello-foo', {
  renderer,
  render () {
    return html`<p>hello foo</p>`
  }
})

createComponent('hello-bar', {
  renderer,
  render () {
    return html`<p>hello bar</p>`
  }
})

// this works
// createComponent('hello-world', {
//   renderer,
//   render () {
//     return html`
//       <hello-foo></hello-foo>
//       <hello-bar></hello-bar>
//     `
//   }
// })

// this does not work
let views = ['<hello-foo></hello-foo>', '<hello-bar></hello-bar>']; //views is a dynamic array, whose elements can be changed
console.log(views.join(''));
createComponent('hello-world', {
  renderer,
  render () {
    return html`
     ${views.join('')}
    `
  }
})
```

**Comment by ducksoupdev** [comment]
Hi @Dan-Do, depending on the renderer, you can achieve the result you are looking for. 

The [`lit-html`](https://docs.ficusjs.org/renderers/lit-html/) renderer can be used with the directives they provide. One such directive is [`unsafeHTML`](https://lit.dev/docs/templates/directives/#unsafehtml) - this will render a string as HTML rather than text.

See this Codepen for an example - https://codepen.io/ducksoupdev/pen/vYebdem?editors=1010

**Comment by Dan-Do** [comment]
Thank you. I just know it :)
